import type { MetadataRoute } from "next";

const SITE_URL = (() => {
  const env = process.env.NEXT_PUBLIC_SITE_URL;
  if (env) return env.replace(/\/$/, "");
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`;
  return "http://localhost:3000";
})();

/**
 * `robots.txt` — allow the public marketing + profile surface, disallow the
 * owner-only dashboard, admin, API, and the Sentry monitoring tunnel. Point
 * crawlers at `/sitemap.xml` (generated by `app/sitemap.ts`).
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/admin", "/dashboard", "/api", "/monitoring"],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
